# Generated by Django 2.1.2 on 2018-10-28 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_tittle', models.CharField(max_length=20)),
                ('b_date', models.DateField(default=datetime.date(1996, 1, 1))),
                ('b_read_count', models.IntegerField(default=0)),
                ('b_comment', models.IntegerField(default=0)),
                ('b_isDel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('h_gender', models.IntegerField(default=0)),
                ('h_comment', models.CharField(max_length=200)),
                ('h_isDel', models.BooleanField(default=False)),
                ('h_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo')),
            ],
        ),
    ]
